### ISSUE TITLE
Terminal screenshot color

### ISSUE THREAD

**Issue by cig0** [romkatv/dotfiles-public#1]
Could you share the color palette you used for the screenshot? Thanks in advance.

**Comment by romkatv** [comment]
The screenshot was taken with the config as it is in the repo ([Powerlevel10](https://github.com/romkatv/powerlevel10k) documentation has installation instructions but I suppose you already know that) in GNOME Terminal on Ubuntu 18.04 with default settings.

If this doesn't answer you question, please give me a hint how to answer it.

Edit: Here's a screenshot of my Terminal preferences:

![terminal](https://user-images.githubusercontent.com/1282067/55461856-c9a6a180-55f5-11e9-845e-3c650eea5356.png)

**Comment by cig0** [comment]
Man... of course, you mention everywhere you're using Ubuntu 😖

I should hit the sheets more often that I'm willing to -- thanks!
