### ISSUE TITLE
A question about a line in .zshrc

### ISSUE THREAD

**Issue by edshamis** [romkatv/dotfiles-public#13]
Hello, Roman. Can you please explain what `*:` and `(N)` does in
```
  for file in $ZDOTDIR/.zsh_history.*:$z4h_ssh_host(N); do

```
How does it work together? I'm curious for my zsh learning

**Comment by romkatv** [comment]
`:` is not special in file names. I use it as a separator between the name of the client machine and the server. An example of a history file would be `~/.zsh_history.adam:db`. This is history of commands that I ran while physically logged in to "adam" (my Linux desktop) and working over SSH on "db" (a server that runs a database).

See https://github.com/romkatv/zsh4humans/blob/master/tips.md#persistent-and-shared-command-history.

**Comment by edshamis** [comment]
Thanks for the explanation!

**Comment by romkatv** [comment]
You are welcome.
