### ISSUE TITLE
Git status prompt isn't showing for private/public repos

### ISSUE THREAD

**Issue by edshamis** [romkatv/dotfiles-public#14]
Is it expected behavior?

**Comment by romkatv** [comment]
Please describe what you do, what you expect and what you observe.

**Comment by edshamis** [comment]
I started to test your dotfiles mechanic. Everything works except when I switch to public/private repos no git status (the green one) is show in the prompt

**Comment by romkatv** [comment]
How do you switch to public/private repos?

If you answer the questions I posted above, it would save time.

**Comment by edshamis** [comment]
Sorry for lack of details. I swich with defined keybinds. Private/public repos are located in home dir. Actually I copied all your mechanics as described in the readme.

I expect the green git status to reflect the status when I switch to public/private

**Comment by romkatv** [comment]
Can you switch to the public repo, run the following command and post a screenshot that includes prompt and the output?

```zsh
cd && bindkey '^P' && typeset -p GIT_DIR POWERLEVEL9K_LEFT_PROMPT_ELEMENTS && functions prompt_my_git_dir && git rev-parse --show-toplevel
```

**Comment by edshamis** [comment]
Mind that I changed the keybind
```
❯ cd && bindkey '^[\\' && typeset -p GIT_DIR POWERLEVEL9K_LEFT_PROMPT_ELEMENTS && functions prompt_my_git_dir && git rev-parse --show-toplevel
"^[\\\\" toggle-dotfiles
export GIT_DIR=/home/ed/.dotfiles-public
typeset -a POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=( os_icon context dir my_git_dir vcs newline prompt_char )
prompt_my_git_dir () {
        emulate -L zsh
        [[ -n $GIT_DIR ]] || return
        local repo=${GIT_DIR:t}
        [[ $repo == .git ]] && repo=${GIT_DIR:h:t}
        [[ $repo == .dotfiles-(public|private) ]] && repo=${repo#.dotfiles-}
        p10k segment -b 0 -f 208 -t ${repo//\%/%%}
}
/home/ed

 ed@Sun-Moon-PC  ~ public                                                                                                                                                 ❯
```
[screenshot](https://i.imgur.com/wLVQiQr.png)

**Comment by romkatv** [comment]
How about this (when the public repo is active)?

```zsh
typeset -pm 'VCS_*|*gitstatus*|GITSTATUS*'
```

P.S.

You can drag and drop images to the edit box. No need for imgur.

**Comment by edshamis** [comment]
I edited the previous replay regarding keybind.
The output of `typeset -pm 'VCS_*|*gitstatus*|GITSTATUS*'`:
```
                                                                                                                                                                    13:18:04❯ typeset -pm 'VCS_*|*gitstatus*|GITSTATUS*'
typeset -i GITSTATUS_DAEMON_PID_POWERLEVEL9K=7966
typeset VCS_STATUS_COMMIT_SUMMARY=''
typeset GITSTATUS_CACHE_DIR=/home/ed/.cache/zsh4humans/v5/cache/gitstatus
typeset VCS_STATUS_RESULT=norepo-sync
typeset -F _p9k__gitstatus_start_time=1665479496.7985222340
typeset GITSTATUS_XTRACE_POWERLEVEL9K=/dev/null
typeset GITSTATUS_DAEMON_LOG_POWERLEVEL9K=/dev/null
typeset -A _p9k__gitstatus_last=( [/mnt/c/Users/ed/Always]=$'99a600b405b4079c9fccb6cd21e772a6a50ffff1\C-@main\C-@main\C-@origin\C-@https://github.com/edshamis/always.git\C-@\C-@570\C-@0\C-@5\C-@0\C-@0\C-@0\C-@1\C-@0\C-@0\C-@0\C-@0\C-@0\C-@\C-@0\C-@0\C-@0\C-@\C-@\C-@0\C-@0\C-@0\C-@0' [GIT_DIR:/home/ed/.dotfiles-public]='' )
typeset VCS_STATUS_COMMIT_ENCODING=''
typeset _gitstatus_plugin_dir_p9k_=/home/ed/.cache/zsh4humans/v5/powerlevel10k/gitstatus

 ed@Sun-Moon-PC  ~ public                                                                                                                                                 ❯
```

**Comment by romkatv** [comment]
Try adding `GITSTATUS_LOG_LEVEL=DEBUG` to `~/.zshrc` and then check gitstatusd logs with this:

```zsh
cat -- $GITSTATUS_DAEMON_LOG_POWERLEVEL9K
```

**Comment by edshamis** [comment]
Added debug option, relaunched zsh, switched to public. BTW does gitstatus take GIT_WORK_TREE into the account?
[log](https://gist.githubusercontent.com/edshamis/bcdd0cacfcb07bc9b6ca93371957ba2b/raw/aedc3eddcabbcdf623770d9d24a403a530d5f96c/gitstatus.log)

**Comment by romkatv** [comment]
The log doesn't illuminate.

I'm afraid I've exhausted the time budget that I can afford to spend here. Closing as Won't Fix. If you ever find out the reason it doesn't work for you, please post an update.

**Comment by edshamis** [comment]
Can you please advise how can I proceed with debug? Can I run `gitstutusd` from command line to test?
I found this [issue](https://github.com/romkatv/powerlevel10k/issues/491), do you think it's related? 
Any way, thank you a lot for your time and efford!

**Comment by romkatv** [comment]
The best thing would be to follow the installation instructions verbatim from scratch. If you follow everything down to the letter and it doesn't work, I'll take a look.

**Comment by edshamis** [comment]
Found it.
I did as you said: on fresh user installed z4h, configured p10k with wizard, cloned your dotfiles-public. Issue persisted. 

Then I took your p10k.zsh from dotfiles and it worked. So it looks like the p10k wizard issue

**Comment by romkatv** [comment]
OK, problem solved then. There is no issue in the wizard. You cannot take my dotfiles, change something, and expect everything to keep working. These dotfiles are literally just my dotfiles. They work as they are. You can modify them if you know what you are doing of course.

**Comment by romkatv** [comment]
Note that the bulk of my dotfiles is private. I could in theory move many things over to the public repo but it's not something I really care about at the moment.

**Comment by edshamis** [comment]
Totally fine, I had fun making it work. No expectations)) Thanks for your time!
