### ISSUE TITLE
Font Problem

### ISSUE THREAD

**Issue by akefirad** [romkatv/dotfiles-public#3]
I installed zsh, oh-my-zsh, powerlevel10k, powerline (from the ubuntu repository), and purepower. But my terminal looks like:
![Screenshot from 2019-04-10 09-06-33](https://user-images.githubusercontent.com/2142363/55862353-937a9c00-5b78-11e9-9a33-43ff5326dc24.png)
Any help?

**Comment by romkatv** [comment]
A regular Powerline font won't do, you'll need a patched one. There are several solutions. I'll list them from easiest to the most difficult.

**Option I**

Set `PURE_POWER_MODE=portable` in your `~/.zshrc` before you source `~/.purepower`. The prompt won't look as fancy but it'll work with any font.

**Option II**

1. Copy fonts from https://github.com/romkatv/dotfiles-public/tree/master/.local/share/fonts/NerdFonts to `~/.local/share/fonts/NerdFonts`.
2. Update your font cache by running `sudo fc-cache -fv`.
3. Set your default monospace font to "MesloLGS Nerd Font Mono". If using GNOME, you can do it by running `gsettings set org.gnome.desktop.interface monospace-font-name 'MesloLGS Nerd Font Mono 11'`. If you don't have `gsettings`, install it with `sudo apt install libglib2.0-bin`.

**Option III**

Follow the guide at https://github.com/bhilburn/powerlevel9k/wiki/Install-Instructions#step-2-install-a-powerline-font.

**Comment by akefirad** [comment]
Thanks.

**Comment by romkatv** [comment]
@akefirad For the benefit of future readers that might find this issue, what did you end up doing?

**Comment by akefirad** [comment]
I did what you said and it did the trick. But I kinda don't like the look :D (and reseting using gsettings didn't revert it back). So I'm gonna try it again with a fresh env. See how it goes. Will update the ticket.

**Comment by romkatv** [comment]
If you want to revert the default monospace font back to what it was, you can run this command:

```zsh
gsettings set org.gnome.desktop.interface monospace-font-name 'Ubuntu Mono 13'
```

('Ubuntu Mono 13' is the default monospace font on Ubuntu 18.04.)

You can also install Tweaks application that provides GUI for changing system fonts (among other things):

```zsh
sudo apt-get install gnome-tweak-tool
gnome-tweaks
```

Once the Tweaks window appears, navigate to Fonts in the left panel.

**Comment by akefirad** [comment]
Didn't work :confused: 
```
# gsettings get org.gnome.desktop.interface monospace-font-name
'Ubuntu Mono 13'
```
But still the look is the same.

**Comment by romkatv** [comment]
Do I understand it correctly that the first `gsettings set` command you typed had an effect of changing the font in Terminal but the second `gsettings set` command didn't have any effect? That's interesting.

Maybe your default monospace font wan't Ubuntu Mono 13? Maybe you don't even have Ubuntu Mono 13? Either way, using `gnome-tweaks` should make things clearer.

**Comment by akefirad** [comment]
That's right. The very first `set` command changed it and now nothing reverts it back :smile: 
I don't know what is wrong here. I also test `reset` command, no success.
Will dig into it later and update the ticket.

**Comment by romkatv** [comment]
`reset` cannot affect this.

Please do run `gnome-tweaks` and set the font form the UI. It has a drop-down menu that shows which fonts you actually have.

**Comment by romkatv** [comment]
By the way, you aren't calling `gsettings` as root, are you? It won't work if you call it as root.

**Comment by akefirad** [comment]
No I do not :)
