### ISSUE TITLE
Autocompletion seems to mess up the BUFFER

### ISSUE THREAD

**Issue by ghost** [romkatv/dotfiles-public#4]
Hi.

It appears as if the purepower theme messes up the BUFFER line on tab completion.
Do you have the same problem? If so, do you have any solution?

Here is a video for better visualization: https://asciinema.org/a/Li33Mrf0V0vOjH7qbhlOOtrvn , it should only be available for 7 days though.

I have ofc tried isolating the purepower/powerlevel10k plugins to make sure the problem comes from it.

**Comment by romkatv** [comment]
> It appears as if the purepower theme messes up the BUFFER line on tab completion.

Just to clarify, you are typing `foo<space><tab>` in that screencast, right?

> Do you have the same problem?

No. Also, your prompt looks different from mine right from the start.

> I have ofc tried isolating the purepower/powerlevel10k plugins to make sure the problem comes from it.

What were the results of your trying to isolate this problem?

If you could tell me how to reproduce this, I'll debug it. If you are using Linux, please give me a command similar to this: https://github.com/romkatv/powerlevel10k#docker-playground. If on FreeBSD (as your userpic suggests) or MacOS, give me something like this:

```zsh
git clone https://github.com/romkatv/powerlevel10k.git /tmp/powerlevel10k
(cd /tmp/powerlevel10k && curl -fsSLO https://raw.githubusercontent.com/romkatv/dotfiles-public/master/.purepower)
echo '
  source /tmp/powerlevel10k/.purepower
  source /tmp/powerlevel10k/powerlevel10k.zsh-theme' >/tmp/powerlevel10k/.zshrc
env -i TERM=$TERM LANG=$LANG ZDOTDIR=/tmp/powerlevel10k zsh
```

If executing these commands doesn't reproduce the problem you are having, figure out what's different in your environment, add those bits to the snippet and post it here.

**Comment by romkatv** [comment]
Friendly ping. I'll be happy to debug this issue if you provide a bit more info. Right now I have nothing to go with.

**Comment by ghost** [comment]
I have actually resolved the issue. I cannot remember exactly what the variable was (or even find it again in the zsh docs) but some variable related to RPROMPT caused it when set to 1. I only remember it had something to do with mutiline prompts, but I can't actually find out what it was. Unsetting it solved the problem. Thank you though.
