### ISSUE TITLE
Unable to source: command not found: custom_rprompt

### ISSUE THREAD

**Issue by natsumi** [romkatv/dotfiles-public#7]
Ater installing / sourcing purepower. and starting a new shell I get the following error
`command not found: custom_rprompt`

The prompt is then shown as `${${${KEYMAP:-0}:#vicmd}:+❯}${${$((!${#${KEYMAP:-0}:#vicmd})):#0}:+❮}`

**Comment by romkatv** [comment]
Are you using Powerlevel9k or Powerlevel10k?

If you are using Powerlevel10k, how did you install it?

If you are using Powerlevel9k, you either need to switch to [Powerlevel10k](https://github.com/romkatv/powerlevel10k/#installation) or add `PURE_POWER_USE_P10K_EXTENSIONS=0` to your `~/.zshrc` before sourcing `~/.purepower`. This option will turn off vi keymap integration, so your prompt symbol will always be '❯'. Your prompt will also be 10-100 times slower with Powerlevel9k compared to Powerlevel10k. This is not the fault of Pure Power. Powerlevel9k is slow with any styling.

**Comment by romkatv** [comment]
I see in your dotfiles that you are using zprezto. Powerlevel10k is bundled with zprezto, so you don't have to install it separately (although you can if you want; just make sure to keep it up to date).

1. Update your zprezto installation including all its submodules.
2. Add `zstyle ':prezto:module:prompt' theme 'powerlevel10k'` to your `.zpreztorc`.

Now you can remove `source ~/.powerlevel10k/powerlevel10k.zsh-theme` line from `.zshrc`.

Keep the `source ~/.purepower` line.

Let me know whether it works for you.

**Comment by natsumi** [comment]
It was my outdated zprezto installation.  I went ahead and followed your suggestions and everything is working now.

Totally escaped me to upgrade.

Thanks for all your help.  I love the theme.

**Comment by romkatv** [comment]
Thanks for the confirmation!
