### ISSUE TITLE
virtualenv (python) isn't displayed  [.purepower]

### ISSUE THREAD

**Issue by karipov** [romkatv/dotfiles-public#8]
I am in need of displaying whether I have a virtualenv working or not.

For the time being, the only information I've found from my research is that I can enable it as one of the plugins inside the .purepower script:

```
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir virtualenv vcs)
```

However, implementing this does not do justice to the theme:
![](https://telegra.ph/file/23caf23f555454e3cf499.jpg)
(Please ignore the fact that I don't have a patched powerline font)

Would there be any way to fix this to fit into the Pure Power theme and philosophy? Thanks.

**Comment by romkatv** [comment]
Please do the following:

1. Update powerlevel10k.

2. Download the latest version of `.purepower`.

```zsh
( cd && curl -fsSLO https://raw.githubusercontent.com/romkatv/dotfiles-public/master/.purepower )
```

3. Open `~/.purepower` with a text editor and uncomment `virtualenv` in `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` array.

4. (Optional) If you don't want to see Python version in your prompt, change `POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=true` to `POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=false`.

Let me know whether it works for you.

> Please ignore the fact that I don't have a patched powerline font.

Smart choice :+1:

**Comment by romkatv** [comment]
By the way, if that long `user@host` segment on the right hand side isn't useful to you, you can get rid of it by commenting out `context` in `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` array.

**Comment by karipov** [comment]
This has definitely worked, and displays the virtualenv prompt beautifully:
![](https://telegra.ph/file/78c7914d4a8f3a88a3425.jpg)

I know this might be a different question, but, after installing a patched Powerline font (I've tried FiraCode and Meslo LG S), along with enabled ligatures in iTerm2, I still see the `\4! ?` as shown above on the git (vcs) prompt. Is that normal?

Many thanks.

**Comment by romkatv** [comment]
> I still see the \4! ? as shown above on the git (vcs) prompt. Is that normal?

Everything in there is normal except for backslash. Git status should be `!4 ?`, which means you have 4 unstaged changes (e.g., you've changed 4 files without doing `git add`) and some untracked files (you've created new files without doing `git add`).

Did you update your Powerlevel10k as I suggested?

> 1. Update powerlevel10k.

:point_up: 

If you've cloned Powerlevel10k, you need to go to the `powerlevel10k` directory, type `git pull` and then restart ZSH. The backslash will then disappear.

> after installing a patched Powerline font

Note that Pure Power config doesn't use any Powerline symbols, so installing a Powerline font won't change anything.

**Comment by karipov** [comment]
Fixed everything. Loving Pure Power. Thank you!

**Comment by romkatv** [comment]
Awesome :fireworks:

Thanks for confirming!
