### ISSUE TITLE
Statements must be separated by &, ; or a newline

### ISSUE THREAD

**Issue by muuvmuuv** [romkatv/dotfiles-public#9]
I'm seeing this in VS Code in https://github.com/romkatv/dotfiles-public/blob/master/.purepower:

![Bildschirmfoto 2019-07-10 um 15 52 55](https://user-images.githubusercontent.com/11534760/60974751-e9eba800-a32a-11e9-9a57-50096141496d.png)

Is this something I should worry about or can I disable the warning somehow?

**Comment by romkatv** [comment]
This code is correct and I like it the way it is. Apparently your VS Code is checking `.purepower` against some style guide that I've never heard of in which it is said that writing `foo && bar` in ZSH is bad (this is nonsense by the way). Or maybe the linter's parser is broken, who knows? There are many style guides out there and I have no intention satisfying all or any of them in my config files. Whether you should worry I cannot tell.

**Comment by muuvmuuv** [comment]
Np, I was just wondering where this is coming from but makes sense. Then I'll open an issue on the linters maintainer site, thank you.
